### ISSUE TITLE
Possible to use VaultPropertySource, with non hard-coded endpoint?

### ISSUE THREAD

**Issue by nilo85** [spring-projects/spring-vault#122]
Hi,

I am trying to use VaultPropertySource annotation, in combination with configuration provided vault endpoint. but as VaultPropertySource seems to be forcefully load the VaultTemplate from the AbstractVaultConfiguration before context is initialised, my vaultUri is null.

Here is my VaultConfiguration:
```
@Configuration
public class VaultConfiguration extends AbstractVaultConfiguration {

    @Value("${vault.uri}")
    private URI vaultUri;

    @Value("${vault.token}")
    private String vaultToken;


    @Override
    public VaultEndpoint vaultEndpoint() {
        return VaultEndpoint.from(vaultUri);
    }

    @Override
    public ClientAuthentication clientAuthentication() {
        return new TokenAuthentication(vaultToken);
    }


}
```
Here is my property source definition
```
@VaultPropertySource(
        value = "secret/myapp/authentication",
        propertyNamePrefix = "secret.authentication."
)
```

Here is the error I get:
```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'vaultPropertySource#0': Cannot resolve reference to bean 'vaultTemplate' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'vaultTemplate' defined in class path resource [app/authentication/configuration/VaultConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.vault.core.VaultTemplate]: Factory method 'vaultTemplate' threw exception; nested exception is java.lang.IllegalArgumentException: URI must not be null
```

**Comment by mp911de** [comment]
Using `@VaultPropertySource` requires an early initialization to provide configuration data as early as possible to the context so components are initialized with the appropriate configuration. Early initialization happens before any post-processors (such as `AutowiredAnnotationBeanPostProcessor` which processes `@Value` injection) get registered that's why your `@Value` annotation is not considered for injection.

You can use `Environment` to resolve property placeholders yourself. `AbstractVaultConfiguration` is `ApplicationContextAware` so the code would look like:

```java
@Configuration
public class VaultConfiguration extends AbstractVaultConfiguration {


    @Override
    public VaultEndpoint vaultEndpoint() {
        return VaultEndpoint.from(getEnvironment().getRequiredProperty("vault.uri", URI.class));
    }

    @Override
    public ClientAuthentication clientAuthentication() {
        return new TokenAuthentication(getEnvironment().getRequiredProperty("vault.token"));
    }
}
```

I'd like to keep this ticket open to investigate whether we can do something to improve about when property sources are created and registered.

**Comment by mp911de** [comment]
May I close this ticket or is there anything else I can assist you with?

**Comment by nilo85** [comment]
Hi. Sorry, forgot to answer. Thank you very much, your explaination makes a
lot of sesne.

Please close :)
