### ISSUE TITLE
cannot override the login url in AppRoleAuthentication 

### ISSUE THREAD

**Issue by netwein** [spring-projects/spring-vault#123]
In the AppRoleAuthentication the predefind login url is "/auth/{mount}/login" and then I can replace the {mount} but my cloud provider supplies we a different login url of "v1/auth/approle/login".
Is there a way to override the url?

**Comment by mp911de** [comment]
There's no possibility to override the full URL right now. How does your URL look like? Do you have an example? 

You could create your own authentication based on `ClientAuthentication` or, if your Vault server has a namespace prefix for your account, then the best would be creating a customized [`RestTemplate`](https://github.com/spring-projects/spring-vault/blob/master/spring-vault-core/src/main/java/org/springframework/vault/client/VaultClients.java#L89) that renders custom URLs.

**Comment by netwein** [comment]
I don't need to override the full url, just the path on in.
the predefind login url is "/auth/{mount}/login"  but in the vault I'm using it is defined as "/v1/auth/approle/login".  

If I try to define a Custom App Role Authentication or a customized RestTemplate it means I will need to override EnvironmentVaultConfiguration. 
How can I do that?

**Comment by mp911de** [comment]
I think you don't need to to anything because `v1` belongs to Vault itself. All requests issued by Spring Vault are prefixed with a base-url following the scheme `(http|https)://(hostname):(port)/v1` which renders as example to `https://localhost:8200/v1`.

If you want to subclass `EnvironmentVaultConfiguration`, then create an own configuration class extending `EnvironmentVaultConfiguration` and annotate it with `@Configuration`. Then, override `public ClientAuthentication clientAuthentication()` and return your implementation and import your config class instead of `EnvironmentVaultConfiguration`.

**Comment by netwein** [comment]
you where right! login works great and so the fetching of the properties from it.
Another question: do in spring-vault we have the ability to refresh beans in runtime?

**Comment by mp911de** [comment]
There's nothing special in Spring Vault. You can use Spring Cloud's [`@RefreshScope`](http://cloud.spring.io/spring-cloud-static/docs/1.0.x/spring-cloud.html#_refresh_scope) but you should use Spring Boot and [Spring Cloud Vault](https://github.com/spring-cloud/spring-cloud-vault) for this purpose. If you need access to most recent config data, then you rather should access `Environment` directly instead of `@Value` injection.

Closing this issue as the original question is answered.
