### ISSUE TITLE
Support AppRole pull mode

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-vault#132]
Add support for pull mode by fetching a wrapped `secret_id` with an initial token.

See also: [“Secret id missing” error while connecting to Vault using Spring cloud vault]( https://stackoverflow.com/questions/45978288/secret-id-missing-error-while-connecting-to-vault-using-spring-cloud-vault/45983670#45983670).

**Comment by vincent-lenair** [comment]
Hi,

I am facing the same issue, I need to use pull mode to get RoleID and SecretID.
I am planning to make changes in AppRoleAuthentication to handle Push/Pull mode, introducing 2 new parameters: AppRole and RoleToken that would allow the application to use pull mode in order to get RoleID and/or SecretID

The logic would be the following:

```
IF RoleID AND SecretID, use push mode (current behavior)
ELSE IF AppRole AND RoleToken
        IF NOT RoleID, pull RoleID from Vault API using AppRole and RoleToken
        IF NOT SecretID, pull SecretID from Vault API using AppRole and RoleToken
```

then authenticate using RoleID and SecretID to get secrets as usual

**Comment by mp911de** [comment]
Thanks for your comment. I'm a bit torn on the implementation. In general, your approach would work but the thing is, that pull mode requires additional context and would incorporate I/O. 

I'm thinking about another AppRole authentication implementation class along with separate options that allow pulling a roleId and secretId from either wrapped responses or the authentication backend itself.

I would describe the options with `VaultToken` and a `Source` object for RoleId and SecretId so the actual `ClientAuthentication` can then decide where to fetch the data from, like you described it above.

**Comment by vincent-lenair** [comment]
Hi,

Thanks for your reply.

Can you explain what you mean by "pull mode requires additional context and would incorporate I/O"
I haven't started working on it, but I by looking at it I though I would be able to get the role ID and secret ID using RestOperations, and then get the VaultToken in the same way as we do in AppRoleAuthentication.createTokenUsingAppRole

I can implement a new type of authentication, something like a RoleNameAuthentication, using the AppRole and RoleToken in order to get the RoleID and SecretID using the pull mode but I think this solution is less generic.

Not sure this is what you had in mind

**Comment by mp911de** [comment]
Pull mode fetches at least SecretId from Vault – either from a wrapped response or from `approle/role/(role)/secret-id`. Compared to `AppRoleAuthentication`, that's an additional HTTP request to be made. I guess it makes sense to provide something similar for RoleId.

You need a token for the request and you need to know whether it's a request for a wrapped response or whether you need to fetch the `secret_id` directly from the authentication backend. The additional configuration parameters are the context I was referring to.

**Comment by mp911de** [comment]
Done.
