### ISSUE TITLE
@VaultPropertySource should support custom PropertyTransformer

### ISSUE THREAD

**Issue by vrudikov** [spring-projects/spring-vault#178]
Current logic of `@VaultPropertySource` allows us to use only `PropertyTransformers.propertyNamePrefix` for property name transformation
I think we could improve it and add `propertyTransformer` to `@VaultPropertySource` to allow us to use custom `PropertyTransformer`s

Because PropertyTransformer should be an implementation i propose to use custom bean name(as we already have for `@VaultPropertySource.vaultTemplate`) or maybe you have any suggestions of how it can be implemented

**Comment by mp911de** [comment]
Extending `@VaultPropertySource` adds more complexity and another possibility to achieve the same as when registering a `PropertySource` yourself. The purpose of `@VaultPropertySource` is to give Vault-based property management a jumpstart and to not require to do the registration dance yourself unless you're required to do so.

The other aspect you already mentioned is that you require an instance of a `PropertyTransformer`. I wouldn't recommend registering these as beans because a lot of tiny instances easily clutters your application context.

If there is sufficient demand for a more simplified registration and configuration of property sources, maybe it's worth to provide a public API to pick up `VaultPropertySource` beans and register these with the `Environment`.

**Comment by vrudikov** [comment]
Ok. Got it, sir. Agree with you
