### ISSUE TITLE
Expose renewSelf, revokeSelf, lookupSelf

### ISSUE THREAD

**Issue by mikebell90** [spring-projects/spring-vault#201]
Currently these are scattered in internal code. But they are quite useful for those managing their own token lifeTime.

Right now renew, revoke fail in opsForToken unless you have rights to the general renew/revoke endpoint.

**Comment by mp911de** [comment]
There are no `renewSelf` or `revokeSelf` methods. What's the actual issue you want to solve?

**Comment by mikebell90** [comment]
Well, there are flows where a user of the spring-vault might want to renewSelf, revokeSelf, or lookupSelf. You have ALL of these, buried inside service classes like the LifeCycleAwareSessionManager, instead of exposing them in opsForSys.

Here's a use case:

* When someone gets a wrapped token and unwraps with CubbyholeAuthentication, you are also supposed to (vault best practices) validate the path is reasonable, and that appears to have the policies you expect etc. 
* Someone might want to write their own SessionManager with different methodologies. Why should they rewrite this.

etc. Point is -self endpoints exist so most people can use any token with default policy to execute these command. But you dont publicly expose them, leading to needless "escape hatchiung" with doWithSession. 

Don't get me wrong, doWithSession is a fine escape hatch for unsupported calls to vault etc. It's just a fair amount of duplication of effort

On another side, would you be interested in a PR adding the wrapped token creation to vault token request (this is done with an extra header)?

**Comment by mp911de** [comment]
Thanks a lot for your explanation. I'm a bit torn on self-operations as they concern mainly session-related aspects. I'd rather shoot for something session-related that abstracts token-related self-operations on session level and that can be reused.

Regarding the second item, wrapped token creation: Feel free to submit a pull request for wrapped regular/orphan token creation. On a related note, we could introduce `VaultWrappingTemplate` since wrapping is becoming more and more a first-class citizen with Vault. I filed #208 for that purpose.

**Comment by mikebell90** [comment]
Ok, will look.

**Comment by mikebell90** [comment]
I agree btw that SessionManagers should be the route of the "80%", but I feel like these xxxx-self ops should be in opsForSys too.

**Comment by mp911de** [comment]
We decided to not introduce `…Self` methods on the Template now. We will revisit this topic at a later time.
