### ISSUE TITLE
Support for custom load order

### ISSUE THREAD

**Issue by nov1n** [spring-projects/spring-vault#456]
## Observed behavior
By default the VaultPropertySources are added [_after_](https://github.com/spring-projects/spring-vault/blob/5a47421a037d2fde188dc194e32abd4a72b258cd/spring-vault-core/src/main/java/org/springframework/vault/annotation/VaultPropertySourceRegistrar.java#L98) all the [default](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html) Spring property sources.

## Desired behavior
For our usecase, we'd like to have properties from Vault take priority over the local `application.properties` file.

## Context
We're running the 1.x branch which has a [bug](https://github.com/spring-projects/spring-vault/blob/1.1.x/spring-vault-core/src/main/java/org/springframework/vault/annotation/VaultPropertySourceRegistrar.java#L84) that's fixed in 2.x causing `VaultPropertySources` to be added again even if they are already registered. This prevents an otherwise possible workaround using a custom `BeanFactoryPostProcessor` that reads `VaultPropertySource` beans from the Spring environment, and adds them as property sources in the right order. Implementing `PriorityOrdered` on the processor also does not solve this issue, because it will still run before `VaultPropertySourceRegistrar`.

Is there any way to achieve a  functionality?

**Comment by mp911de** [comment]
Have you tried using [Spring Cloud Vault](https://github.com/spring-cloud/spring-cloud-vault) to initialize `PropertySource`s before the actual application context gets started?

**Comment by nov1n** [comment]
We don't currently use `spring-cloud-vault`. How exactly do these two projects relate? From the README's both state they `provide client-side support for externalized configuration` 🤔

**Comment by mp911de** [comment]
Spring Vault implements the actual client along with authentication/session support and a few extra features such as Spring Data repositories and `@VaultPropertySource`.

Spring Cloud Vault hooks into the bootstrap context to provide credentials for a more Spring Boot-oriented approach with databases, integrations (AWS, RabbitMQ) and property sources before the actual application starts up. This allows using secrets from Vault for Spring Boot bootstrapping. Spring Cloud Vault allows you to configure the Vault integration through `bootstrap.properties`.

Let me know whether this makes sense.

**Comment by nov1n** [comment]
That makes sense. So IIUC customising the load order is not so much a use-case for `spring-vault` as it is for `spring-cloud-vault`.

A followup question: When using `spring-cloud-vault` would it be possible for vault property sources to have a priority between two Spring property sources, e.g:
1. Overrides
2. Environment variables
3. Vault properties from `/kv/foo-team/secrets`
4. Vault properties from `/kv/bar-service/secrets`
5. `application.properties`

such that Vault properties override `application.properties`.

Because `spring-vault` covers most of our other use-cases and is very simple to use, I'm wondering whether it is really necessary to use `spring-cloud-vault` instead.

**Comment by mp911de** [comment]
> customising the load order is not so much a use-case for spring-vault as it is for spring-cloud-vault

Spring Cloud Vault *is the* load order customization because it already runs before starting the actual context. The alternative is providing an `ApplicationContextInitializer` that does already what Spring Cloud is doing.

Within Spring Cloud Vault, you can provide a `VaultConfigurer` bean to register secret backend paths. These registrations are added in the same order as PropertySources.

Now, the block of `PropertySource`s registered by Spring Cloud is either added first, last or after, depending on `spring.cloud.config.overrideSystemProperties`, `spring.cloud.config.allowOverride`, and `spring.cloud.config.overrideNone`.

* `allowOverride=false` or (`overrideNone=false` and `overrideSystemProperties=true`): Registered as first `PropertySource`
* `overrideNone=false`: Registered as last `PropertySource`
* `overrideSystemProperties=true`: Registered before System properties
* `overrideSystemProperties=false`: Registered after System properties

**Comment by mp911de** [comment]
With these measures, we keep functionality as-is without duplicating efforts of Spring Cloud Vault.

**Comment by nov1n** [comment]
That makes sense, thanks for your explanation 👍
