### ISSUE TITLE
Question: approle auth and pull mode

### ISSUE THREAD

**Issue by ask4gilles** [spring-projects/spring-vault#569]
Hi Mark,

Looking at [Hahsicorp Doc](https://www.vaultproject.io/docs/auth/approle.html#pull-and-push-secretid-modes) for the approle auth, they suggest that the Pull mode is the most secured approach.

In your documentation [here](https://docs.spring.io/spring-vault/docs/current/reference/html/#vault.authentication.approle) and [here](https://cloud.spring.io/spring-cloud-vault/reference/html/#_approle_authentication), you suggest to override the `ClientAuthentication` by providing our own bean and use the pull mode for both `role-id` and `secret-id`:

```
@Configuration
class AppConfig extends AbstractVaultConfiguration {

    // …

    @Override
    public ClientAuthentication clientAuthentication() {

        VaultToken initialToken = VaultToken.of("…");
        AppRoleAuthenticationOptions options = AppRoleAuthenticationOptions.builder()
                .appRole("…")
                .roleId(RoleId.pull(initialToken))
                .secretId(SecretId.pull(initialToken))
                .build();

        return new AppRoleAuthentication(options, restOperations());
    }

    // …
}
```

1. What's this `initialToken` and how do you get it?
2. Regarding the matrix [here](https://cloud.spring.io/spring-cloud-vault/reference/html/#_approle_authentication) what's the most secure choice to make in order to protect the `role-id` and `secret-id`?
3. Does all the above make [this kind of approach](https://github.com/spring-projects/spring-vault/issues/221#issuecomment-373926578) for approle irrelevant?

Many thanks for your answers!

**Comment by mp911de** [comment]
Spring Vault supports all variants for AppRole (provided, pull, wrapped, absent) for Role ID and Secret ID. 

> the SecretID can be kept confidential from all parties except for the final authenticating client by using Response Wrapping.

This section refers to provided Role ID and wrapped Secret ID obtained from a wrapped response.

The example above with `RoleId.pull(…)` and `SecretId.pull(…)` makes two requests to Vault in order to obtain both identifiers. `initialToken` takes a similar role as in response wrapping, it should be only valid for two calls and then get invalidated. Role-wise, it should only be allowed to obtain Role ID and Secret ID from the auth-backend.

The approach to ensure a maximum of protection would be the use of wrapped Role ID and Secret ID which requires two different unwrapping tokens. If either of the wrapped parts isn't accessible then this is already an indicator for either a consumed or an expired wrapping token.

In general, retrieval of role-id and secret-id from within Vault is generally called pull mode while there is [Read AppRole Role ID from the auth backend](https://www.vaultproject.io/api/auth/approle#read-approle-role-id) and the wrapped variant. Same applies for Secret ID.

Let me know whether this helps.

**Comment by ask4gilles** [comment]
Mark, it does help thanks. I'll dig into this.
