### ISSUE TITLE
Provide a possibility to instantiate a VaultTemplate using VaultEndpoint, ClientAuthentication and a custom RestTemplate

### ISSUE THREAD

**Issue by L7R7** [spring-projects/spring-vault#572]
I'm currently working on integrating a Spring Boot app with Vault using Spring Vault. In my particular case the address to the Vault instance as well as the Vault token are provided externally (read: Spring Vault doesn't need to take care of this). At the moment, I provide a `VaultTemplate` bean like so:
```java
@Bean
VaultTemplate vaultTemplate(@Value("${vault-client.vaultAddr}") URI vaultAddress, @Value("${vault-client.clientToken}") String clientToken) {
  return new VaultTemplate(VaultEndpoint.from(vaultAddress), new TokenAuthentication(clientToken));
}
```

Since the `VaultTemplate` is using a `RestTemplate` under the hood, I was wondering if it's possible to provide a `RestTemplate` for the `VaultTemplate` to use together with a given address and a token. I see that there is a constructor taking just a `RestTemplateBuilder`, but that seems to be for a different use case.

Does it make sense to provide a constructor that takes a `VaultEndpoint`, a `ClientAuthentication` and a `RestTemplate`?

**Comment by mp911de** [comment]
`VaultTemplate` has two modes of operation: authenticated and unauthenticated. Additionally, all HTTP requests require a pause path to be configured in the `RestTemplate`. These assumptions do not allow for holding up the contracts when handing in a custom RestTemplate. Adding a ClientAuthentication contributes to the complexity as typically, you want to use authentication with proper session management. The token is added to each authenticated request by using a request interceptor in `RestTemplate` which requires a modification of the `RestTemplate` object. 

That being said, using a provided `RestTemplate` isn't straightforward. 

We introduced recently the builder API to provide a maximum level of flexibility to customize the `RestTemplate`. 

Can you explain your use-case why you need to pass in a `RestTemplate` and cannot use the existing API?

**Comment by L7R7** [comment]
Thanks for the explanation. In my case, I would like to use an instrumented `RestTemplate` that allows me to measure request latencies for example

**Comment by mp911de** [comment]
I understand that instrumenting `RestTemplate` can be a bit uneasy. On the other side, there's not much we can do in Spring Vault to alter how the session token gets injected as almost all operation methods on `VaultTemplate` and friends use `doWithSession(…)` that gets called with the `RestTemplate`.

Ideally, for metering you would instrument `ClientHttpRequestFactory` instead of `RestTemplate` to limit metering only to the HTTP interaction which would provide a more portable approach.

As a workaround, you should be able to subclass `VaultTemplate` and override `doWithSession(…)` and `doWithVault(…)`.  You would need to attach the session token interceptor to the `RestTemplate` that is associated with `doWithSession(…)`.

**Comment by L7R7** [comment]
Ok, I see. Thank you for your feedback! I will see what I can come up with for my needs. I'll close the PR

**Comment by mp911de** [comment]
Closing this issue as the suggested workaround seems to be fine and there was no followup stating otherwise.
