### ISSUE TITLE
Azure Authentication - Configurable Resource ID

### ISSUE THREAD

**Issue by infa-szhong** [spring-projects/spring-vault#583]
It looks like for Azure MSI Authentication, Spring requests the JWT token from this URL: "http://169.254.169.254/metadata/identity/oauth2/token?resource=https://vault.hashicorp.com&api-version=2018-02-01". It seems that this is not configurable.

Would it be possible to make the Vault resource ID parameter configurable to something other than the value "https://vault.hashicorp.com"? This might be needed in the case of having multiple Vault resources as their IDs must be unique.

(Copied from [spring-cloud-vault/issues/451](https://github.com/spring-cloud/spring-cloud-vault/issues/451) because I realized the change should be here instead)

**Comment by mp911de** [comment]
Right now, you can specify `instanceMetadataUri` when using `AzureMsiAuthenticationOptionsBuilder`:

```java
AzureMsiAuthenticationOptions.builder().instanceMetadataUri(URI.create("http://169.254.169.254/metadata/identity/oauth2/token?resource=https://hello.world&api-version=2018-02-01").build();
```

Since the resource can be directly configured in the [Vault azure auth backend](https://www.vaultproject.io/api-docs/auth/azure) it would make sense to provide a shortcut method that accepts the `resource` identifier. Calling a `resource(…)` builder method would set internally `instanceMetadataUri`.

Do you want to submit a pull request?

**Comment by infa-szhong** [comment]
I think configuring the instanceMetadataUri is enough for my use case. So in this case the only change needed is in spring-cloud-vault. I'm going to make the change over there to the `VaultProperties` class.

**Comment by mp911de** [comment]
Closing this request as we're going to apply a change in Spring Cloud Vault.
