### ISSUE TITLE
VaultPropertySource fails on null ApplicationContext

### ISSUE THREAD

**Issue by ndpar** [spring-projects/spring-vault#634]
I use `VaultPropertySource` to implement PropertySource API programmatically. The code looks like this (in Kotlin)

    class VaultProcessor : EnvironmentPostProcessor {
        override fun postProcessEnvironment(environment: ConfigurableEnvironment, application: SpringApplication) {
            ...
            val template = VaultSecretStore(...).vaultTemplate() // VaultSecretStore extends AbstractVaultConfiguration
            val source = VaultPropertySource(template, path)
            environment.propertySources.addFirst(source)
        }
    }

This class/method is invoked when `ApplicationContext` is not available yet. And it works in `spring-vault-core:2.2.2.RELEASE` for example, i.e. one can call `AbstractVaultConfiguration.vaultTemplate()` before `ApplicationContext` is set.

But `spring-vault-core:2.3.1` expects `ApplicationContext` to be set

    SpringApplication.reportFailure(856) : Application run failed java.lang.IllegalStateException: ApplicationContext must be set before accessing getBeanFactory()
        at org.springframework.util.Assert.state(Assert.java:76)
        at org.springframework.vault.config.AbstractVaultConfiguration.getBeanFactory(AbstractVaultConfiguration.java:276)
        at org.springframework.vault.config.AbstractVaultConfiguration.getClientFactoryWrapper(AbstractVaultConfiguration.java:283)
        at org.springframework.vault.config.AbstractVaultConfiguration.vaultTemplate(AbstractVaultConfiguration.java:131)

If it's not a bug, then my implementation needs to be re-written. Can you please provide pointers to/examples of how to populate Spring Boot environment using `VaultPropertySource` programmatically in spring-vault version 2.3.x?

**Comment by mp911de** [comment]
Subclasses of `AbstractVaultConfiguration` must be initialized by calling `setApplicationContext(…)` as we're obtaining beans from the context, specifically:

* `ClientFactoryWrapper`
* `RestTemplateFactory`
* `RestTemplateCustomizer`,
* `SessionManager`
* `VaultTemplate`
* `TaskSchedulerWrapper`

Since Spring Cloud Vault 3.0, we integrate with Spring Boot's ConfigData API for easier bootstrapping.

If you want to fully programmatically obtain a `VaultPropertySource` without using managed beans, then I'd suggest spinning up `VaultTemplate` yourself using a `VaultEndpoint` and `SessionManager`/`ClientAuthentication`. These may require additional components such as a `ThreadPoolTaskScheduler` if you want to periodically renew the session token.
