### ISSUE TITLE
Add support for credential rotation of static-role database credentials

### ISSUE THREAD

**Issue by igouss** [spring-projects/spring-vault#645]
![image](https://user-images.githubusercontent.com/339/113940692-d903eb00-97cb-11eb-9b20-60451f3735e3.png)

Hi, when I request a secret it's `secrets.getLeaseDuration() == 0`, but I think it should not be a Lease.none() but a `Lease.fromTimeToLive(Duration.ofSeconds((Integer) secrets.getData().get("ttl")));`

But I'm not sure. Can I ask you if the issue with my vault configuration or with the library?

see https://github.com/spring-projects/spring-vault/blob/2.3.x/spring-vault-core/src/main/java/org/springframework/vault/core/lease/SecretLeaseContainer.java#L386

I think according to https://learn.hashicorp.com/tutorials/vault/database-creds-rotation?in=vault/secrets-management
"ttl" should be used.

**Comment by igouss** [comment]
vault response looks like this:
```
{
  "request_id": "19598f33-0eae-041a-9345-d5a7ad5936d2",
  "lease_id": "",
  "renewable": false,
  "lease_duration": 0,
  "data": {
    "last_vault_rotation": "2021-04-07T16:51:53.872438247Z",
    "password": "A1a-blah",
    "rotation_period": 86400,
    "ttl": 64403,
    "username": "abe-readonly"
  },
  "wrap_info": null,
  "warnings": null,
  "auth": null
}
```

**Comment by mp911de** [comment]
I have a hard time understanding what you're asking for. Right now, static roles aren't renewed/rotated in Spring Vault's `SecretLeaseContainer`. Specifically, these aren't leases in the sense of regular Vault credentials with leases, these are credentials rotated within Vault where the client obtains only a view along with the current password and the remaining TTL.

We support rotate-only secrets for Key-Value v1 backends to re-fetch the secret after the cache TTL has expired. However, static roles are renewed after the TTL has expired. It requires the client to ask Vault after the expiry (not before, otherwise the client would still see the previous password) for credentialsrotation.

**Comment by mp911de** [comment]
Revisiting this one, static roles are an approach to serve compliance issues and not so much an approach where each application instance receives its own login that can be destroyed if there was a disclosure of credentials or someone compromised the system.

That being said, we do not plan to implement this feature as there are already solutions in place that address the need for dynamic database secrets.
