### ISSUE TITLE
Keystore's certificate chain derived from Vault issue-certificate lacks CA authority certificate

### ISSUE THREAD

**Issue by ppmspetrovic** [spring-projects/spring-vault#648]
Thank you for Spring Vault, @mp911de.  Massively helpful, *especially* in how the library offers a clean way to create a Keystore from the Vault `pki/issue` response.  I was not looking forward to rolling my own version of this with BouncyCastle, which is quite possible, but drudgery.  These creature comforts are one of the many reasons I value your work.

One feature enhancement, however, which I believe is very helpful, if not essential.  Imagine this signing scenario:

Root CA named R signs intermediate CA C1.  C1 signs Vault's PKI CSR, making Vault CA C2.  The leaf Vault generates at `pki/issue`, is L.  The full chain is therefore `R -> C1 -> C2 -> L`.

AFAICT, when Spring Vault builds the Keystore certificate chain associated with the acquired private key, it currently does not take into consideration the `pki/issue` response field `ca_chain`.  Instead, Spring Vault honors `issuing_ca`, which is necessary but not sufficient.  Why should Spring Vault honor `ca_chain`?  Consider that the Vault PKI API allows Vault operators to [indicate the CA certificate that *signed* Vault's signing certificate](https://www.vaultproject.io/api/secret/pki#parameters-5).  Using the nomenclature above,  the Vault operator dictates that `ca_chain` would be the concatenation of C2 and C1, in PEM format, knowing that C1 signed C2.

If Spring Vault honored `ca_chain`, it can build a Keystore certificate chain that is sufficiently rich to allow selection of a client certificate (via a custom Java X509 KeyManager) during TLS setup, based solely on the ultimate Root CA R.  A postulated business server that challenges a Java client for a client certificate would indicate during TLS setup that it accepts any certificate rooted in a Root CA R.  Such a server may quite possibly be ignorant of  C1 and/or C2, but it knows about R (it has to know at least that much).

So by honoring `ca_chain` when building the Keystore, Spring Vault gives a TLS client enough material to select which client cert to return based on a single root CA.

Thanks for reading this far.

**Comment by ppmspetrovic** [comment]
I am not 100% certain this is as great an enhancement as I had argued.  One could solve the same problem by adding C1 to the acceptable issuers on the server side.  In so doing the server would send two acceptable issuers:  C1 and the Root R.

Interested in what others think.

Thanks.

**Comment by mp911de** [comment]
Thanks for reaching out. I think the reason for the current arrangement is that back then, when we built the support for PKI, `ca_chain` was either not documented or not present in earlier vault versions. Also, since our tests cases didn't cover multi-level CA arrangements, the issue never came up. 

We could extend CertificateBundle to be ca-chain-aware, probably we need to look into certificate splitting, but we should have most of the code to make it work. For `KeyStore` creation, we can introduce two constants (full chain, issuer certificate) to control which certificates include in the `KeyStore`.

The utilities to create a `KeyStore` are intended for convenient usage so that a server or client could be launched for e.g. TLS usage without the need of further `KeyStore` customization.

**Comment by ppmspetrovic** [comment]
Thank you, Mark.  Look forward to whatever you come up with.

**Comment by mp911de** [comment]
That's in place now. Please give the upcoming 2.3.3 snapshot a try.
